version: "3.7"

services:
  app:
    working_dir: "/app"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "."
        target: "/app"
    ports:
      - "8080:8080"
      - "2345:2345"
