openapi: 3.0.0
info:
  title: Swagger Practice
  version: 1.0.0
servers:
  - url: http://localhost/
    description: development
paths:
  /hello:
    get:
      operationId: hello
      responses:
        200:
          description: OK
          schema:
            type: string
            description: response text

 